# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'evernote_test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for evernote_test
pod 'EvernoteSDK', '~> 3.0'
pod 'HTMLEntities', :git => 'https://github.com/Kitura/swift-html-entities.git'

end
